import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
LANGCHAIN_TRACING_V2 = os.getenv("LANGCHAIN_TRACING_V2")
LANGCHAIN_API_KEY = os.getenv("LANGCHAIN_API_KEY")
ELASTIC_SEARCH_HOST = os.getenv("ELASTIC_SEARCH_HOST") 
ELASTIC_SEARCH_URL = os.getenv("ELASTIC_SEARCH_URL") 
ELASTIC_SEARCH_USER = os.getenv("ELASTIC_SEARCH_USER") 
ELASTIC_SEARCH_PASSWORD = os.getenv("ELASTIC_SEARCH_PASSWORD") 